name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  ENV_FILE: environment.yml

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:

    - name: Setting conda path
      run: echo "::add-path::${HOME}/miniconda3/bin"

    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup environment and build pandas
      run: |
        chmod +x ci/setup_env.sh
        ci/setup_env.sh
      if: always()

    - name: Make code checks executable
      run: chmod +x ci/code_checks.sh
      if: always()

    - name: Looking for unwanted patterns
      run: ci/code_checks.sh patterns
      if: always()

    - name: Linting
      run: ci/code_checks.sh lint
      if: always()

    - name: Dependencies consistency
      run: ci/code_checks.sh dependencies
      if: always()

    - name: Checks on imported code
      run: ci/code_checks.sh code
      if: always()

    - name: Running doctests
      run: ci/code_checks.sh doctests
      if: always()

    - name: Docstring validation
      run: ci/code_checks.sh docstrings
      if: always()

    - name: Typing validation
      run: ci/code_checks.sh typing
      if: always()

    - name: Testing docstring validation script
      run: pytest --capture=no --strict scripts
      if: always()